### ISSUE TITLE
Update TIGER 2019 files on nominatim.org

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#1610]
Root cause of https://github.com/openstreetmap/Nominatim/issues/1603 was outdated TIGER 2019 data on nominatim.org.

on nominatim.org:
```
ls | wc -l
3134
cat *.sql | wc -l
31744151
```

should be:
```
ls | wc -l
3233
cat *.sql | wc -l
33967042
```

Can you re-upload the corrected data mentioned in https://github.com/openstreetmap/Nominatim/pull/1474#issuecomment-534767099 ?

**Comment by lonvia** [comment]
Done.

**Comment by blucompassai** [comment]
Thank you guys .. what is the good download link for 2019 tiger data now : 

https://nominatim.org/data/ still shows last update 2019-09-25.

Much appreciate.

**Comment by lonvia** [comment]
That's the data @mtmail pointed me to. Size is 1943899591 bytes. Is that wrong?

**Comment by mtmail** [comment]
@lonvia Sorry, I should've double-checked before re-opening. The file is already the correct one.
